### ISSUE TITLE
Release and/or move to backdrop-contrib?

### ISSUE THREAD

**Issue by indigoxela** [drupol/bg_image_formatter#1]
Hi @drupol,

I just wanted to use this module (again), and discovered there's no official release yet.

Have you ever thought about a release and/or moving this cool and lightweight module to backdrop-contrib?

**Comment by drupol** [comment]
Hello,

I think it's on backdrop already ?

**Comment by indigoxela** [comment]
> I think it's on backdrop already

That's what I supposed, too, but it isn't... :wink:

It's still here (github.com/drupol) and there's no release yet.

To have an official module release appearing here: https://backdropcms.org/modules (and in all Backdrop CMS admin areas), you'd need to move it to https://github.com/backdrop-contrib and create a release.

**Comment by indigoxela** [comment]
Hi @drupol,

it seemed easier to start fresh to get this module in contrib :wink:

https://github.com/backdrop-contrib/bg_image_formatter

**Comment by drupol** [comment]
Good, good luck mate.
